# Just running the same shit because I don't feel like building the dumb curl request to test out the GitHub action
name: Test wakeup
on: push
jobs:
#  wakeup:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Wake up
#        run: ./run.sh

  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
#        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get
      run: go get github.com/danpenn/SleepIQ

    - name: Run
      run: go run main.go
      with:
        SLEEPIQ_USER: ${{ secrets.SLEEPIQ_USER }}
        SLEEPIQ_PASS: ${{ secrets.SLEEPIQ_PASS }}