# I will enable or disable this periodically depending on when I'm going on vacation.

name: Wake me up at 730am and 8am on Sunday 5/31 to test this out.
on:
  schedule:
    - cron: '30 11 * * 0'  # 730am Eastern
    - cron: '00 12 * * 0'  # 8am Eastern

jobs:
  wakeup:

    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get
      run: go get github.com/danpenn/SleepIQ

    - name: Run
      run: go run main.go
      env:
        SLEEPIQ_USER: ${{ secrets.SLEEPIQ_USER }}
        SLEEPIQ_PASS: ${{ secrets.SLEEPIQ_PASS }}