name: Wake me up at 730am and 8am on weekdays (US Eastern time)
on:
  schedule:
    - cron: '00 10 * * 1-5'  # 6am Eastern
    - cron: '30 10 * * 1-5'  # 630am Eastern
    - cron: '00 11 * * 1-5'  # 7am Eastern
    - cron: '30 11 * * 1-5'  # 730am Eastern
    - cron: '00 12 * * 1-5'  # 8am Eastern

jobs:
  wakeup:

    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get
      run: go get github.com/danpenn/SleepIQ

    - name: Run
      run: go run main.go
      env:
        SLEEPIQ_USER: ${{ secrets.SLEEPIQ_USER }}
        SLEEPIQ_PASS: ${{ secrets.SLEEPIQ_PASS }}
